### PR TITLE
modify makefile to add scalability of number of workers 

### PR DESCRIPTION
**Pull request by minchen57**
Now in the directory project-code/hadoop-python-docker-sentiment
one could run the analysis using a fully distributed cluster with n workers by the following command:
`make all worker=n`

@bsobolik  Please try with some n you like when you have time, (e.g. n=3).

### CODE REVIEW

**Comment by minchen57** [comment]
never saw this before, it says
`Container killed on request. Exit code is 137[2018-04-18 09:52:52.364]
[2018-04-18 09:52:53.712]Container exited with a non-zero exit code 137. [2018-04-18 09:52:53.861]
[2018-04-18 09:52:58.464]Killed by external signal`

Did you stop containers in another terminal or something similar? it sounds like a interruption from external.

**Comment by minchen57** [comment]
Another possibility is resource limitation. Please try again with make all worker=2

**Comment by bsobolik** [comment]
Should I kill it? it's still running.

**Comment by minchen57** [comment]
Yes, you can use `make down` in another terminal to shut it down. 
before running a new one, make sure you stop and rm all containers (in case the make down does not work) using:
`docker stop $(docker ps -a -q)`
`docker rm $(docker ps -a -q)`

**Comment by bsobolik** [comment]
OK, I restarted it. Do you get this warning:

```

18/04/18 10:52:58 WARN util.NativeCodeLoader: Unable to load native-hadoop
library for your platform... using builtin-java classes where applicable
```

**Comment by minchen57** [comment]
Yes, all the time, I did not find the native-hadoop library compiled in 64-bits for 2.9.0, I searched the community and got no result. It is replied that we can basically ignore the warnings and it won't affect anything including performance. 

The only hadoop version that I was able to achieve without this warning is 2.7.5.

**Comment by minchen57** [comment]
@bsobolik Additional information:
I am trying make all worker=3 on my macbook pro now (8GB ram, 2.7Ghz i5), it got stuch at first Mapreduce job with

**Comment by bsobolik** [comment]
It worked for me with 2. Go ahead and merge if you want. but I'll let you do it in case you want to incorporate a fix for the 3 worker issue first. I will email you the log file. Should we collect these somewhere?

**Pull request merged**
