### PR TITLE
Min

### PR DESCRIPTION
**Pull request by minchen57**
Hi Bertolt,
It took me some time to figure out how to merger master into my branch and how to push to my branch and then issue a PR. Hope I did not mess up.

In addition, I add in the project-code folder the files to run sentiment analysis using one container. If you have time, could you try it on your end? just follow the steps in readme:
1. create the image
2. start the container
3. run the bash script

It may take around 2 hours for the entire process (on my mac), hopefully it is a neither too long nor too short benchmarking task. You could do this before your dinner and come back and checker later. Please let me know if it works. I got accuracy around 82.5% which is expected according to the paper i wrote.

I tried to assign this to you so you can test it.

### CODE REVIEW

**Comment by bsobolik** [comment]
I'm trying it out now.

**Comment by bsobolik** [comment]
I got an error on the third step: 
```bash
(2.7.13) BKS-MBP:hadoop-python bsobolik$ docker run -it minchen57/minchen57/hadoop-docker-python-sentiment /etc/bootstrap.sh -bash
Unable to find image 'minchen57/minchen57/hadoop-docker-python-sentiment:latest' locally
docker: Error response from daemon: pull access denied for minchen57/minchen57/hadoop-docker-python-sentiment, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**Comment by bsobolik** [comment]
I think it's OK for now, but Prof. von Laszewski explicitly say that data should not be on GitHub. Can you put it somewhere else? If you don't have a place, I can upload it to Google Cloud and send you a URL.

**Comment by minchen57** [comment]
I could take care of the data part, give me some time. I need to test how
to download, there is a link actually.

**Comment by minchen57** [comment]
Fixing it.

**Pull request merged**
