### PR TITLE
Min

### PR DESCRIPTION
**Pull request by minchen57**
1. added the word Hadoop to the title
2. added info of several computers that we used for test
3. added several diagrams made to illustrate hadoop deployment we did
4. commented the graphics info of laptops
5. delete duplicated section deployment
6. remove google cloud

@bsobolik , please make sure you are okay with these points. 
for 4, i think we are not using GPU so the graphic info may not be relevant. 
for 6, we are not using it any more right? 
for 3, please take a look at the images started with hadoop-, i will put these in the deployment section, let me know if you have suggestions. 

Further, once you are done with your code and Pi settings, if you have time, could you help me with writing the cloud technology section: FutureSystem Echo, in general, and also if you could find the information on the physical nodes, (at least for the head e006, we can login and use commands to check cpu, memory, OS, etc).

Meanwhile, I will start writing deployment section. hadoop introduction, docker introduction and so on. The benchmarking results section will need to be completed after I get all the results I am testing on, probably tomorrow night.

### CODE REVIEW

**Comment by bsobolik** [comment]
On 4, I included it because it was easy and I thought maybe the GPU was a reason things ran so fast on my laptop. I'd say leave it in. 
On 6, correct, no time for GCP. 

I will help with the writing. I will also go over everything you have written and check spelling and grammar. I'm going to wait until I finish the burn script and write up that and the VM setup before I do that.

**Comment by minchen57** [comment]
Cool, I will finish the docker technology part and deployment of hadoop section by the end of today. Then, what we left is just benchmarking results, discussion and conclusion. Nothing much. By the way, before submission, let's cross check to make sure the reproducibility of the Project Code. Since we have 3 separate sets of code (three folders), we probably need a README in the project-code folder to guide the grader and reader.

**Comment by minchen57** [comment]
I am not sure about that. At least now they are very different in nature. Plus, no ""make"" on Echo

**Comment by bsobolik** [comment]
Got it. I didn't realize that. In that case, I think your initial idea is
the way to go.

**Comment by minchen57** [comment]
We probably need to rename those folders to make it look nicer

**Pull request merged**
